### ISSUE TITLE
it doesn`t work on linux mint 17.2

### ISSUE THREAD

**Issue by springkim** [polohb/gs60-install#1]
i will trying to ubuntu15.10

**Comment by springkim** [comment]
it works on ubuntu 15.10 thanks!

**Comment by polohb** [comment]
Hi, I have only tested my script on Unbutu 15.10.

Linux Mint is based on Ubuntu 14.04 [Mint 17.02 New Features](http://linuxmint.com/rel_rafaela_cinnamon_whatsnew.php).

I think the module to blacklist and install are not the same, for previous version than 15.10, you should use the dkms module : ath10k-dkms.

I don't own anymore this laptop, I can not make any changes to the script and test it.
